### ISSUE TITLE
TCPSyphonServer.app Port Number

### ISSUE THREAD

**Issue by andyjshepherd** [z37soft/INetSyphon_OSX_SDK#1]
Hello! 

I'm very impressed with what you have done here! Great job! Works very well! Low latency & easy to set up.

One small issue I have found is that when opening more than 1 instance of the server. The port number displayed on the GUI window (2nd instance and up), is incorrect from the port number that the syphon server is is actually using. Would it be possible in the future to specify which port to use in the future too?

Thanks

Andy

**Comment by z37soft** [comment]
Hello! Thank you for your report.
Ah, OK. Please give me a few days. I'll decide our specification in multiple instances.
Thanks.

**Comment by andyjshepherd** [comment]
Amazing thank you!!

**Comment by z37soft** [comment]
![tcpsyphonserver](https://cloud.githubusercontent.com/assets/4241465/12892888/30e3475c-cec9-11e5-9cf7-658de26f3335.jpg)

**Comment by z37soft** [comment]
![fullscreen](https://cloud.githubusercontent.com/assets/4241465/12892963/871c7eb8-cec9-11e5-9d96-23af01e38421.jpg)

Well, I think it's correct. If you launch 2 servers on the same host, The port should not be same.
The port number is decided by OS and the software registers it on Bonjour table.

Do you want to set your port number?

**Comment by andyjshepherd** [comment]
<img width="1113" alt="screenshot 2016-02-08 19 34 46" src="https://cloud.githubusercontent.com/assets/17109097/12896657/136a29ee-ce9b-11e5-8c90-81a610ec2b7f.PNG">

Check your bonjour service port numbers. I've attached mine to show you. I'd love to set the port number. This means I can set which content goes to each screen using the raspberry pi client. 

When you open more than 3 clients the port numbers are more away from the one listed on the GUI.

Thanks!

**Comment by z37soft** [comment]
Thank you for your report!
Yes I could reproduce. and fixed it. Could you try new version 1.90(23)?

**Comment by andyjshepherd** [comment]
Perfect thank you! 1.90(23) works perfectly. Did you have any more thoughts on being able choosing the port number?

**Comment by z37soft** [comment]
Thanks. OK, I will make a dialog that you can set manually the port number.
Please wait a week. I've been busy...

**Comment by z37soft** [comment]
![tcpsyphonserver](https://cloud.githubusercontent.com/assets/4241465/13201867/6cb12052-d8be-11e5-939d-c95ad80cd9e8.png)

I uploaded version1.91(24). You can call Preferences dialog from StatusBar Menu. Then you are able to choose manually a network port. and I add a method for TCPServer in my SDK as well.

**Comment by zanza71** [comment]
Hi, is it possible that there is a similar bug in the last 1.92 version? I'm trying to set the port of two server but the result it's the same. The first one use the right number of port (for a  example 7777) but the second one get automatic number of port.

**Comment by z37soft** [comment]
Sorry I forgot to consider your request.
I upload it as v1.92(28). Can you download it again?

Thank you for your report.

**Comment by zanza71** [comment]
Perfect, now it's ok
I duplicated the executable of the server and I modified the Info.plist file. In this way I can create different instance of the server with different preference. When I lunch the servers they keep the right numbers of port. Thank you.
